version: "2"
services:
  elasticsearch:
    ports:
      - ${ES_HTTP_PORT}:9200
  # client:
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - ${HOST_HTTP_PORT}:80
  #     - ${CLIENT_HOST_HTTP_PORT}:3000
