version: "2"
services:
  # React application
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    restart: ${RESTART_POLICY}
    depends_on:
      - api
    ports:
      - ${HOST_HTTP_PORT}:80
    volumes:
      - ${PROJECT_PATH}/client:/client
      - ${PROJECT_PATH}/data:/var/www/data
      - ${PROJECT_PATH}/docker/client/nginx.${MODE}.conf:/etc/nginx/nginx.conf
    environment:
      - MODE=${MODE}
  # React application
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
      args:
        PYTHON_DOCKER_VERSION: ${PYTHON_DOCKER_VERSION}
    restart: ${RESTART_POLICY}
    depends_on:
      - elasticsearch
    volumes:
      - ${PROJECT_PATH}/api:/api
      - ${PROJECT_PATH}/data:/api/data
    environment:
      - MODE=${MODE}
  # Elasticsearch service
  elasticsearch:
    image: elasticsearch:${ES_VERSION}
    restart: ${RESTART_POLICY}
    volumes:
      - ${PROJECT_PATH}/docker/elasticsearch/data:/usr/share/elasticsearch/data
      - ${PROJECT_PATH}/docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "TAKE_FILE_OWNERSHIP=1"
